### ISSUE TITLE
Use modality pixels values and other possible improvements.

### ISSUE THREAD

**Issue by jpambrun** [gradienthealth/gradient_decode_dicom#4]
This is really an awesome little utility project. Thanks a lot for sharing.

A couple things I didn't like: 
* it uses dcmtk to compute display pixels values instead of modality pixel values. This is an odd choice since TF is unlikely to be used for display; makes it difficult (or impossible) to extract the HU values and is waseful.
* convert to uint64, then to the destination type which seems wasteful
* lots of logic (convert_uintn_to_t, then uint64_to_t) in the core loop; that can be moved outside.

I have made the changes [here](https://github.com/jpambrun/gradient_decode_dicom/tree/jpambrun/modalityPixels), but I remove the type checks so it can produce incorrect results if the image signed and the selected dtype is unsigned or too small.

I also added some dockerized build stuff and limited test.

Lets me know if you are interested in integrating some of these changes.

**Comment by Ouwen** [comment]
@jpambrun, sorry for the late response on this and thanks for the suggestions, the decode_dicom_op has been merged to [tensorflow/io](https://github.com/tensorflow/io/blob/master/tensorflow_io/core/kernels/image_dicom_kernels.cc) where these changes can be merged

Outputting the modality values would be wonderful if it can be auto-detected, or providing some header option. We wanted the decoder to be robust to a number of different dicom files and data types so the mode will try its best to map values evenly to a specified dynamic range.

**Comment by jpambrun** [comment]
Thanks for pointing that out. I looked at tensorflow/io's documentation last week for something unrelated and didn't even notice it had dicom decoding.

Anyway, I prefer having the option to get the proper modality values.. I'll keep using the fork for now.
